creds: &creds
  encoding: unicode
  pool: 5
  min_message: warning

  adapter: postgresql
#  host: localhost
#  username: root
#  passowrd: admin

  host: ec2-54-243-250-115.compute-1.amazonaws.com
#  user: jlaqchmrcqhbxk
  username: jlaqchmrcqhbxk
  password: qZ_wQJS8lNI4hhW2m3RCru3OUg
  database: d25crtg5d54amo
  port: 5432



development:
  <<: *creds
#  database: kriogen_inertia_dev

#test:
#  database: kriogen_inert_t

production:
  <<: *creds
#  database: kriogen_inertia
