creds: &creds
  adapter: postgresql
  host: localhost
  username: admin
  password: admin
  min_message: warning

global: &global
  database: inertia_dev
  <<: *creds

development:
  adapter: postgresql
  encoding: unicode
  database: inertia_dev
  username: admin
  password: admin

test:
  adapter: postgresql
  database: inertia_dev
  <<: *creds

production:
  adapter: postgresql
  database: inertia
  <<: *creds
