creds: &creds
  adapter: postgresql
  host: localhost
  user: admin
  passowrd: admin

  #adapter: mysql2
  #host: 127.0.0.1
  #user: root
  #password:

  #adapter: mysql2
  #host: mysql8.websitesource.net
  #username: kriogen_admin
  #password: m3d1ag

  #min_message: warning

development:
  <<: *creds
  database: kriogen_inertia

#test:
#  database: kriogen_inert_t

production:
  <<: *creds
  database: kriogen_inertia
